# MAVROS config for PX4 SITL
/**:
  ros__parameters:
    # Connection
    # SITL: "udp://:14540@127.0.0.1:14557"
    # USB:  "/dev/ttyACM0:921600"
    # UART: "/dev/ttyTHS1:921600"
    fcu_url: "udp://:14540@127.0.0.1:14557"
    gcs_url: ""
    target_system_id: 1
    target_component_id: 1
    fcu_protocol: "v2.0"

    # TF
    local_position:
      frame_id: "world"
      tf:
        send: true
        frame_id: "world"
        child_frame_id: "base_link"

    # Startup
    conn:
      timeout: 30.0

    # Plugin enable/disable
    plugin_allowlist:
      - sys_status
      - sys_time
      - imu
      - local_position
      - vision_pose
      - vision_speed
      - odometry
      - command
      - param
      - rc_io
      - ftp
