/**:
  ros__parameters:
    topics:
      odom_input: "/S550/ground_truth/odom"
      odom_output: "/mavros/local_position/odom"
      pose_output: "/mavros/vision_pose/pose"
    noise:
      position_stddev: 0.005
      angle_stddev: 0.005
      axis_stddev: 0.005
      linear_velocity_stddev_x: 0.028
      linear_velocity_stddev_y: 0.022
      linear_velocity_stddev_z: 0.031
      angular_velocity_stddev_x: 0.071
      angular_velocity_stddev_y: 0.054
      angular_velocity_stddev_z: 0.038
      angular_velocity_colored_noise: false
      apply_noise: true
      delay_ms: 0.0
      z_offset: 0.052
