/**:
  ros__parameters:
    topics:
      odom_input: "/S550/ground_truth/odom"
      odom_output: "/mavros/local_position/odom"
      pose_output: "/mavros/vision_pose/pose"
    noise:
      position_stddev: 0.0005
      angle_stddev: 0.00017
      axis_stddev: 0.005
      linear_velocity_stddev_x: 0.000106
      linear_velocity_stddev_y: 0.000106
      linear_velocity_stddev_z: 0.000106
      angular_velocity_stddev_x: 0.000245
      angular_velocity_stddev_y: 0.000245
      angular_velocity_stddev_z: 0.000245
      apply_noise: true
      z_offset: 0.0